PREFIX core: <https://w3id.org/maestro/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?resource ?label
WHERE {
    ?resource a/rdfs:subClassOf* core:Resource .
    FILTER NOT EXISTS { ?resource core:provides ?skill }
    OPTIONAL { ?resource rdfs:label ?label }
}
ORDER BY ?resource
