# Materialize plant manufacturing ability from product requirements and
# resource-level capability.

PREFIX core: <https://w3id.org/maestro/core#>
PREFIX proc: <https://w3id.org/maestro/process#>
PREFIX prod: <https://w3id.org/maestro/product#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?plant core:canManufacture ?product .
}
WHERE {
    ?plant a core:Plant ;
           core:hasPart ?resource .
    ?resource a/rdfs:subClassOf* core:Resource ;
              core:canPerform ?capability .
    ?product a/rdfs:subClassOf* core:Product ;
             prod:requiresProcess ?process .
    ?process a/rdfs:subClassOf* proc:ManufacturingProcess ;
             proc:requiresCapability ?capability .
}
